CREATE ROLE slavko LOGIN
  PASSWORD 'root'
  NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE stats
    WITH OWNER = slavko
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
